### ISSUE TITLE
Make tinlake.js aware of rate limits in infura, pause requests to not hit rate limit

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/tinlake-ui#405]
e2e tests fail in around 80% of cases because of rate limits, e. g. 

```
1) Scenario: successfully setting the min TIN ratio as admin # features/min-tin-ratio.feature:5
   ✔ Before # features/support/hooks.ts:6
   ✔ Given I am logged into MetaMask as Tinlake admin # features/support/steps.ts:15
   ✔ And I am on the Tinlake investments page # features/support/steps.ts:25
   ✔ And I am connected to Tinlake # features/support/steps.ts:33
   ✖ And the min TIN ratio is set to 10% # features/support/steps.ts:41
       Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32005,"message":"project ID request rate exceeded","data":{"rate":{"allowed_rps":1.2,"backoff_seconds":30,"current_rps":1.3333333333333333},"see":"https://infura.io/docs/ethereum/json-rpc/ratelimits"}}}'
           at /Users/philipstanislaus/Code/centrifuge/e2e-tests/node_modules/tinlake/dist/index.js:31782:29
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:97:5)
   - When I set Min TIN ratio to 11% # features/support/steps.ts:58
   - Then I see that Min TIN ratio component is set to 11% # features/support/steps.ts:76
   ✔ After # features/support/hooks.ts:13
```

**Comment by philipstanislaus** [comment]
Needs migration to ethers since ethjs does not propagate networking errors
